---
abstract: 'Standard Library for Perl 5'
author:
  - 'AWNCORP <awncorp@cpan.org>'
build_requires:
  perl: '5.018'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.033, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Venus
requires:
  perl: '5.018'
resources:
  bugtracker: http://github.com/usevenus/vns/issues
  homepage: https://metacpan.org/dist/Venus
  license: https://opensource.org/licenses/apache-2.0
  repository: git://github.com/usevenus/vns.git
version: '5.00'
x_authority: cpan:AWNCORP
x_generated_by_perl: v5.38.2
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: Apache-2.0
