#!/usr/bin/env perl

package main;

use 5.018;

use strict;
use warnings;

use Cwd ();
use File::Basename ();
use File::Spec ();

our $lib;

BEGIN {
  $lib = File::Spec->catfile(
    File::Basename::dirname(File::Basename::dirname(Cwd::realpath($0))),
    'lib',
  );
}

use lib $lib;

use Venus::Task::Venus::Set;

run Venus::Task::Venus::Set 'vns-set';
