
=head1 NAME

Venus::Task::Venus::Run - vns run

=cut

=head1 ABSTRACT

Task Class for Venus CLI

=cut

=head1 SYNOPSIS

  package main;

  use Venus::Task::Venus::Run;

  my $task = Venus::Task::Venus::Run->new;

  # bless(.., 'Venus::Task::Venus::Run')

=cut

=head1 DESCRIPTION

This package is a task class for the C<vns-run> CLI, and C<vns run>
sub-command.

=cut

=head1 INHERITS

This package inherits behaviors from:

L<Venus::Task::Venus>

=cut

=head1 METHODS

This package provides the following methods:

=cut

=head2 new

  new(any @args) (Venus::Task::Venus::Run)

The new method constructs an instance of the package.

I<Since C<4.15>>

=over 4

=item new example 1

  package main;

  use Venus::Task::Venus::Run;

  my $task = Venus::Task::Venus::Run->new;

  # bless({...}, 'Venus::Task::Venus::Run')

=back

=cut

=head2 perform

  perform() (Venus::Task::Venus::Run)

The perform method executes the CLI logic.

I<Since C<4.15>>

=over 4

=item perform example 1

  # given: synopsis

  package main;

  $task->prepare;

  my $perform = $task->perform;

  # bless(.., 'Venus::Task::Venus::Run')

=back

=over 4

=item perform example 2

  # given: synopsis

  package main;

  $task->prepare;

  $task->parse('brew');

  my $perform = $task->perform;

  # bless(.., 'Venus::Task::Venus::Run')

  # 'perlbrew'

=back

=over 4

=item perform example 3

  # given: synopsis

  package main;

  $task->prepare;

  $task->parse('cpan', 'Venus');

  my $perform = $task->perform;

  # bless(.., 'Venus::Task::Venus::Run')

  # 'cpanm -llocal -qn Venus'

=back

=over 4

=item perform example 4

  # given: synopsis

  package main;

  $task->prepare;

  $task->parse('eval', 'say time');

  my $perform = $task->perform;

  # bless(.., 'Venus::Task::Venus::Run')

  # "perl -Ilib -Ilocal/lib/perl5 -MVenus=true,false,log -E 'say time'"

=back

=over 4

=item perform example 5

  # given: synopsis

  package main;

  $task->prepare;

  $task->parse('lint');

  my $perform = $task->perform;

  # bless(.., 'Venus::Task::Venus::Run')

  # 'perlcritic'

=back

=over 4

=item perform example 6

  # given: synopsis

  package main;

  $task->prepare;

  $task->parse('docs');

  my $perform = $task->perform;

  # bless(.., 'Venus::Task::Venus::Run')

  # 'perldoc'

=back

=cut

=head1 AUTHORS

Awncorp, C<awncorp@cpan.org>

=cut

=head1 LICENSE

Copyright (C) 2022, Awncorp, C<awncorp@cpan.org>.

This program is free software, you can redistribute it and/or modify it under
the terms of the Apache license version 2.0.

=cut